// <auto-generated />
using System;
using Ludo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ludo.Migrations
{
    [DbContext(typeof(LudoDbContext))]
    [Migration("20260512114408_fixSeed")]
    partial class fixSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ludo.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Ludo.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Ludo.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Ludo.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Ludo.Models.ReservationGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationGames");
                });

            modelBuilder.Entity("Ludo.Models.ReservationStations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("StationId");

                    b.ToTable("ReservationStations");
                });

            modelBuilder.Entity("Ludo.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MapLeftPosition")
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal>("MapTopPosition")
                        .HasColumnType("decimal(18,10)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<int?>("StationLevel")
                        .HasColumnType("int");

                    b.Property<int>("StationType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("Station");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R1",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R2",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R3",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R4",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R5",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R6",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R7",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R8",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R9",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 0,
                            StationType = 0,
                            Title = "R10",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 2,
                            StationType = 0,
                            Title = "U1",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 2,
                            StationType = 0,
                            Title = "U2",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 2,
                            StationType = 0,
                            Title = "U3",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 2,
                            StationType = 0,
                            Title = "U4",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 2,
                            StationType = 0,
                            Title = "U5",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 2,
                            StationType = 0,
                            Title = "U6",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 3,
                            StationType = 0,
                            Title = "PR7",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 3,
                            StationType = 0,
                            Title = "PR8",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 3,
                            StationType = 0,
                            Title = "PR9",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            IsActive = true,
                            MapLeftPosition = 0m,
                            MapTopPosition = 0m,
                            PlayerCount = 1,
                            StationLevel = 3,
                            StationType = 0,
                            Title = "PR10",
                            UpdateDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdaterId = 1
                        });
                });

            modelBuilder.Entity("Ludo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("TokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1993, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marall@live.com",
                            Firstname = "دانا",
                            IsActive = true,
                            IsAdmin = true,
                            Lastname = "توانا",
                            Mobile = "09352222222",
                            Password = "admin",
                            UpdateDate = new DateTime(1993, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(1993, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marall@live.com",
                            Firstname = "کاربر",
                            IsActive = true,
                            IsAdmin = false,
                            Lastname = "پشتیبانی",
                            Mobile = "09351111111",
                            Password = "support",
                            UpdateDate = new DateTime(1993, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "support"
                        });
                });

            modelBuilder.Entity("Ludo.Models.Client", b =>
                {
                    b.HasOne("Ludo.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludo.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Ludo.Models.Game", b =>
                {
                    b.HasOne("Ludo.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludo.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Ludo.Models.Log", b =>
                {
                    b.HasOne("Ludo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ludo.Models.Reservation", b =>
                {
                    b.HasOne("Ludo.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludo.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludo.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Ludo.Models.ReservationGame", b =>
                {
                    b.HasOne("Ludo.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludo.Models.Reservation", "Reservation")
                        .WithMany("ReservationGames")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Ludo.Models.ReservationStations", b =>
                {
                    b.HasOne("Ludo.Models.Reservation", "Reservation")
                        .WithMany("ReservationStations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludo.Models.Station", "Station")
                        .WithMany("ReservationStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Ludo.Models.Station", b =>
                {
                    b.HasOne("Ludo.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludo.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Ludo.Models.Reservation", b =>
                {
                    b.Navigation("ReservationGames");

                    b.Navigation("ReservationStations");
                });

            modelBuilder.Entity("Ludo.Models.Station", b =>
                {
                    b.Navigation("ReservationStations");
                });
#pragma warning restore 612, 618
        }
    }
}
